export const customerDataList = [
  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },
  {
    name: "Connor Cho",
    amount: "$32,120",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },

  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },
  {
    name: "Connor Cho",
    amount: "$32,120",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },

  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },

  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },

  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },
  {
    name: "Connor Cho",
    amount: "$32,120",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },

  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },
  {
    name: "Connor Cho",
    amount: "$32,120",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },

  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },
  {
    name: "Connor Cho",
    amount: "$32,120",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },

  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },

  {
    name: "Amber Grant",
    amount: "$12,240",
    "stock-type": "Stocks, & Real Estate",
    status: "debit",
  },
  {
    name: "Ashley Barnt",
    amount: "$13,750",
    "stock-type": "Real Estate & Stock",
    status: "credit",
  },
  {
    name: "Brad Cahoot",
    amount: "$27,020",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
  {
    name: "Chris Leston",
    amount: "$3,570",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "debit",
  },

  {
    name: "Adam Stride",
    amount: "$23,750",
    "stock-type": "Stocks, Bonds & Real Estate",
    status: "credit",
  },
];
